import{S as q,i as c}from"./assets/vendor-IlcmTKtO.js";import v from"https://cdn.jsdelivr.net/npm/axios@1.7.7/+esm";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const a of n.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function r(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerPolicy&&(n.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?n.credentials="include":t.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function s(t){if(t.ep)return;t.ep=!0;const n=r(t);fetch(t.href,n)}})();const E="https://pixabay.com/api/",P="53338306-ce631ed7cad64c964742be59c",A=15;let d=1;function B(){d=1}async function R(o){const e={key:P,q:o.trim(),image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:A,page:d},r=await v.get(E,{params:e});return d+=1,r.data}const I=document.querySelector("#gallery"),h=document.querySelector("#loader"),b=document.querySelector(".load-more");let u=null;function M(o=[]){const e=o.map(({webformatURL:r,largeImageURL:s,tags:t,likes:n,views:a,comments:S,downloads:w})=>`
    <li class="card">
      <a class="gallery__link" href="${s}" title="${t}">
        <img class="thumb" src="${r}" alt="${t}" loading="lazy" />
      </a>
      <div class="meta">
        <span class="stat"><span class="label">Likes:</span> ${n.toLocaleString()}</span>
        <span class="stat"><span class="label">Views:</span> ${a.toLocaleString()}</span>
        <span class="stat"><span class="label">Comments:</span> ${S.toLocaleString()}</span>
        <span class="stat"><span class="label">Downloads:</span> ${w.toLocaleString()}</span>
      </div>
    </li>
  `).join("");gallery.insertAdjacentHTML("beforeend",e),u?u.refresh():u=new q(".gallery a",{captions:!0,captionsData:"alt",captionDelay:200,animationSpeed:200})}function $(){I.innerHTML=""}function O(){h.classList.remove("hidden")}function _(){h.classList.add("hidden")}function H(){b.classList.remove("hidden")}function l(){b.classList.add("hidden")}const N={form:document.querySelector(".form"),input:document.querySelector(".input"),button:document.querySelector(".button"),loadMoreBtn:document.querySelector(".load-more")},{form:x,input:f,button:g,loadMoreBtn:m}=N;let p="",i=0,y=0;function D(){c.warning({title:"Увага",message:"Введіть слово для пошуку.",position:"topRight",timeout:2500})}function z(){c.info({title:"Немає збігів",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",timeout:3200})}function C(o="Сталася помилка. Спробуйте знову."){c.error({title:"Помилка",message:o,position:"topRight",timeout:4e3})}function F(){c.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:3e3})}x.addEventListener("submit",G);m.addEventListener("click",Q);async function G(o){o.preventDefault();const e=f.value.trim();if(!e){D();return}e!==p&&(p=e,B(),i=0,y=0,$()),l(),await L()}async function Q(){await L()}function T(){const o=document.querySelector(".gallery .card");if(!o)return;const e=o.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}async function L(){O(),g.disabled=!0,f.disabled=!0,m.disabled=!0;const o=i===0;try{const e=await R(p),r=Array.isArray(e==null?void 0:e.hits)?e.hits:[],s=Number(e==null?void 0:e.totalHits)||0;if(!r.length&&i===0){z(),l();return}y=s,M(r),i+=r.length,o||T(),i>=y?(l(),F()):H()}catch(e){console.error(e),C(),l()}finally{_(),g.disabled=!1,f.disabled=!1,m.disabled=!1}}
//# sourceMappingURL=index.js.map
