import{S as h,i as p}from"./assets/vendor-IlcmTKtO.js";import b from"https://cdn.jsdelivr.net/npm/axios@1.7.7/+esm";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const L="https://pixabay.com/api/",S="53338306-ce631ed7cad64c964742be59c",E=15;let u=1;function P(){u=1}async function q(s){const o={key:S,q:s.trim(),image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:E,page:u},r=await b.get(L,{params:o});return u+=1,r.data}const f=document.querySelector("#gallery"),m=document.querySelector("#loader");let i=null;function v(s=[]){const o=s.map(({webformatURL:r,largeImageURL:n,tags:e,likes:t,views:a,comments:y,downloads:g})=>`
    <li class="card">
      <a class="gallery__link" href="${n}" title="${e}">
        <img class="thumb" src="${r}" alt="${e}" loading="lazy" />
      </a>
      <div class="meta">
        <span class="stat"><span class="label">Likes:</span> ${t.toLocaleString()}</span>
        <span class="stat"><span class="label">Views:</span> ${a.toLocaleString()}</span>
        <span class="stat"><span class="label">Comments:</span> ${y.toLocaleString()}</span>
        <span class="stat"><span class="label">Downloads:</span> ${g.toLocaleString()}</span>
      </div>
    </li>
  `).join("");f.innerHTML=o,i?i.refresh():i=new h(".gallery a",{captions:!0,captionsData:"alt",captionDelay:200,animationSpeed:200})}function w(){f.innerHTML=""}function $(){m.classList.remove("hidden")}function A(){m.classList.add("hidden")}const _={form:document.querySelector(".form"),input:document.querySelector(".input"),button:document.querySelector(".button")},{form:O,input:l,button:d}=_;let c="";function R(){p.warning({title:"Увага",message:"Введіть слово для пошуку.",position:"topRight",timeout:2500})}function x(){p.info({title:"Немає збігів",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",timeout:3200})}function D(s="Сталася помилка. Спробуйте знову."){p.error({title:"Помилка",message:s,position:"topRight",timeout:4e3})}O.addEventListener("submit",I);async function I(s){s.preventDefault();const o=l.value.trim();if(!o){R();return}o!==c&&(c=o,P(),w()),$(),d.disabled=!0,l.disabled=!0;try{const r=await q(c),n=Array.isArray(r==null?void 0:r.hits)?r.hits:[];if(!n.length){x();return}v(n)}catch(r){console.error(r),D()}finally{A(),d.disabled=!1,l.disabled=!1}}
//# sourceMappingURL=index.js.map
