import{S as v,i as c}from"./assets/vendor-IlcmTKtO.js";import E from"https://cdn.jsdelivr.net/npm/axios@1.7.7/+esm";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))r(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const a of s.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&r(a)}).observe(document,{childList:!0,subtree:!0});function n(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function r(t){if(t.ep)return;t.ep=!0;const s=n(t);fetch(t.href,s)}})();const A="https://pixabay.com/api/",P="53338306-ce631ed7cad64c964742be59c",B=15;async function R(o,e){const n={key:P,q:o.trim(),image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:B,page:e};return(await E.get(A,{params:n})).data}const h=document.querySelector("#gallery"),b=document.querySelector("#loader"),L=document.querySelector(".load-more");let u=null;function I(o=[]){const e=o.map(({webformatURL:n,largeImageURL:r,tags:t,likes:s,views:a,comments:w,downloads:q})=>`
    <li class="card">
      <a class="gallery__link" href="${r}" title="${t}">
        <img class="thumb" src="${n}" alt="${t}" loading="lazy" />
      </a>
      <div class="meta">
        <span class="stat"><span class="label">Likes:</span> ${s.toLocaleString()}</span>
        <span class="stat"><span class="label">Views:</span> ${a.toLocaleString()}</span>
        <span class="stat"><span class="label">Comments:</span> ${w.toLocaleString()}</span>
        <span class="stat"><span class="label">Downloads:</span> ${q.toLocaleString()}</span>
      </div>
    </li>
  `).join("");h.insertAdjacentHTML("beforeend",e),u?u.refresh():u=new v(".gallery a",{captions:!0,captionsData:"alt",captionDelay:200,animationSpeed:200})}function M(){h.innerHTML=""}function $(){b.classList.remove("hidden")}function O(){b.classList.add("hidden")}function _(){L.classList.remove("hidden")}function l(){L.classList.add("hidden")}const H={form:document.querySelector(".form"),input:document.querySelector(".input"),button:document.querySelector(".button"),loadMoreBtn:document.querySelector(".load-more")},{form:N,input:d,button:g,loadMoreBtn:f}=H;let m="",i=0,p=0,y=1;function x(){c.warning({title:"Увага",message:"Введіть слово для пошуку.",position:"topRight",timeout:2500})}function D(){c.info({title:"Немає збігів",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",timeout:3200})}function z(o="Сталася помилка. Спробуйте знову."){c.error({title:"Помилка",message:o,position:"topRight",timeout:4e3})}function C(){c.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:3e3})}N.addEventListener("submit",F);f.addEventListener("click",G);async function F(o){o.preventDefault();const e=d.value.trim();if(!e){x();return}e!==m&&(m=e,y=1,i=0,p=0,M()),l(),await S()}async function G(){await S()}function Q(){const o=document.querySelector(".gallery .card");if(!o)return;const e=o.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}async function S(){$(),g.disabled=!0,d.disabled=!0,f.disabled=!0;const o=i===0;try{const e=await R(m,y),n=Array.isArray(e==null?void 0:e.hits)?e.hits:[],r=Number(e==null?void 0:e.totalHits)||0;if(!n.length&&i===0){D(),l();return}p=r,I(n),i+=n.length,y+=1,o||Q(),i>=p?(l(),C()):_()}catch(e){console.error(e),z(),l()}finally{O(),g.disabled=!1,d.disabled=!1,f.disabled=!1}}
//# sourceMappingURL=index.js.map
